language: node_js
node_js:
  - "9"
  - "8.4"
  - "8.3"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
  - "4.0.0"
  - "0.12"
  - "0.12.0"
  - "0.10"
  - "0.10.0"
  - "0.11"
  - "0.11.16"
  - "0.11.8"
  - "0.11.4"
  - "0.11.3"
  - "0.11.2"
  - "0.11.1"
  - "0.11.0"
  - "0.9"
  - "0.9.6"
  - "0.9.5"
  - "0.9.4"
  - "0.9.3"
  - "0.9.2"
  - "0.8"
  - "0.8.21"
  - "0.8.14"
  - "0.8.12"
  - "0.8.11"
  - "0.8.10"
  - "0.8.9"
